name: Test Runner

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: self-hosted

    steps:
      - name: Check runner
        shell: pwsh
        run: Write-Host "Runner is working on $env:RUNNER_OS"

      - name: Show PAYARA_HOME
        shell: pwsh
        run: Write-Host "PAYARA_HOME = $env:PAYARA_HOME"
